//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationForm()
        {
            this.ApplicationStatusHistories = new HashSet<ApplicationStatusHistory>();
            this.AppointmentSchedules = new HashSet<AppointmentSchedule>();
            this.BiometricDatas = new HashSet<BiometricData>();
            this.DocumentChecklists = new HashSet<DocumentChecklist>();
            this.FileForwardingLogs = new HashSet<FileForwardingLog>();
            this.PassportBooklets = new HashSet<PassportBooklet>();
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
            this.PoliceVerificationRequests = new HashSet<PoliceVerificationRequest>();
            this.PoliceVerificationReports = new HashSet<PoliceVerificationReport>();
            this.PSKDecisionDetails = new HashSet<PSKDecisionDetail>();
            this.PSKVisitDetails = new HashSet<PSKVisitDetail>();
        }
    
        public string ARN { get; set; }
        public int ApplicantID { get; set; }
        public string ApplicationType { get; set; }
        public string SchemeType { get; set; }
        public string CurrentStatus { get; set; }
        public System.DateTime DateOfSubmission { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<System.DateTime> GrantingDecisionDate { get; set; }
        public Nullable<int> GrantingOfficerID { get; set; }
        public Nullable<System.DateTime> PVCompletedDate { get; set; }
        public Nullable<System.DateTime> ApplicationCloseDate { get; set; }
    
        public virtual Applicant Applicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationStatusHistory> ApplicationStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentSchedule> AppointmentSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiometricData> BiometricDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentChecklist> DocumentChecklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileForwardingLog> FileForwardingLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassportBooklet> PassportBooklets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoliceVerificationRequest> PoliceVerificationRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoliceVerificationReport> PoliceVerificationReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSKDecisionDetail> PSKDecisionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSKVisitDetail> PSKVisitDetails { get; set; }
    }
}
