//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationStatusHistory
    {
        public int StatusID { get; set; }
        public string ARN { get; set; }
        public string StatusCode { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
