//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentSchedule
    {
        public int ScheduleID { get; set; }
        public string ARN { get; set; }
        public int PSKLocationID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public string BookingStatus { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
