//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceLog
    {
        public int LogID { get; set; }
        public int AttendanceID { get; set; }
        public string PunchType { get; set; }
        public System.DateTime PunchTime { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual AttendanceHeader AttendanceHeader { get; set; }
    }
}
