//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiometricData
    {
        public int BiometricID { get; set; }
        public string ARN { get; set; }
        public string PhotoReference { get; set; }
        public string FingerprintReference { get; set; }
        public System.DateTime CaptureTimestamp { get; set; }
        public string CaptureDeviceID { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
