//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchLog
    {
        public int DispatchID { get; set; }
        public int PassportID { get; set; }
        public string ConsignmentNumber { get; set; }
        public System.DateTime DispatchDate { get; set; }
        public string CourierAgency { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryFailureReason { get; set; }
        public Nullable<System.DateTime> RTSReceivedDate { get; set; }
    
        public virtual PassportBooklet PassportBooklet { get; set; }
    }
}
