//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentChecklist
    {
        public int DocCheckID { get; set; }
        public string ARN { get; set; }
        public string DocumentType { get; set; }
        public bool RequiredFlag { get; set; }
        public bool SubmittedFlag { get; set; }
        public Nullable<bool> VerifiedFlag { get; set; }
        public string DeficiencyDetails { get; set; }
        public Nullable<System.DateTime> VerificationTimestamp { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
