//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileForwardingLog
    {
        public int ForwardLogID { get; set; }
        public string ARN { get; set; }
        public System.DateTime ForwardingDate { get; set; }
        public string FromAuthority { get; set; }
        public string ToAuthority { get; set; }
        public string ForwardingPurpose { get; set; }
        public string TrackingReference { get; set; }
        public Nullable<System.DateTime> ExpectedReturnDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
