//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class passportEntities : DbContext
    {
        public passportEntities()
            : base("name=passportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<ApplicationForm> ApplicationForms { get; set; }
        public virtual DbSet<ApplicationStatusHistory> ApplicationStatusHistories { get; set; }
        public virtual DbSet<AppointmentSchedule> AppointmentSchedules { get; set; }
        public virtual DbSet<BiometricData> BiometricDatas { get; set; }
        public virtual DbSet<DispatchLog> DispatchLogs { get; set; }
        public virtual DbSet<DocumentChecklist> DocumentChecklists { get; set; }
        public virtual DbSet<FileForwardingLog> FileForwardingLogs { get; set; }
        public virtual DbSet<PassportBooklet> PassportBooklets { get; set; }
        public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual DbSet<PoliceVerificationReport> PoliceVerificationReports { get; set; }
        public virtual DbSet<PoliceVerificationRequest> PoliceVerificationRequests { get; set; }
        public virtual DbSet<PSKDecisionDetail> PSKDecisionDetails { get; set; }
        public virtual DbSet<PSKVisitDetail> PSKVisitDetails { get; set; }
    }
}
