//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportBooklet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PassportBooklet()
        {
            this.DispatchLogs = new HashSet<DispatchLog>();
        }
    
        public int PassportID { get; set; }
        public string ARN { get; set; }
        public string PassportNumber { get; set; }
        public string BookletType { get; set; }
        public int BookletSize { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime DateOfExpiry { get; set; }
        public int PrintingUnitID { get; set; }
        public System.DateTime PrintingDate { get; set; }
        public string QualityControlStatus { get; set; }
        public Nullable<int> QCInspectorID { get; set; }
        public string ePassportChipStatus { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatchLog> DispatchLogs { get; set; }
    }
}
