//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceVerificationReport
    {
        public int PVReportID { get; set; }
        public int PVRequestID { get; set; }
        public string ARN { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string VerificationOutcome { get; set; }
        public bool AddressVerifiedFlag { get; set; }
        public bool BackgroundClearFlag { get; set; }
        public string ReportDetails { get; set; }
        public string InvestigatingOfficerID { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
        public virtual PoliceVerificationRequest PoliceVerificationRequest { get; set; }
    }
}
