//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceVerificationRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PoliceVerificationRequest()
        {
            this.PoliceVerificationReports = new HashSet<PoliceVerificationReport>();
        }
    
        public int PVRequestID { get; set; }
        public string ARN { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string PoliceStationCode { get; set; }
        public string VerificationType { get; set; }
        public string PVSendStatus { get; set; }
        public string TrackingID { get; set; }
        public Nullable<System.DateTime> TargetCompletionDate { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoliceVerificationReport> PoliceVerificationReports { get; set; }
    }
}
