//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSKDecisionDetail
    {
        public int DecisionID { get; set; }
        public string ARN { get; set; }
        public string DecisionOutcome { get; set; }
        public string DecisionReason { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DecisionTimestamp { get; set; }
        public int GrantingOfficerID { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
