//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSKVisitDetail
    {
        public int VisitID { get; set; }
        public string ARN { get; set; }
        public int PSKLocationID { get; set; }
        public System.DateTime ActualVisitTime { get; set; }
        public string TokenNumber { get; set; }
        public string CounterA_Status { get; set; }
        public Nullable<int> CounterA_OfficerID { get; set; }
        public string CounterB_Status { get; set; }
        public Nullable<int> CounterB_OfficerID { get; set; }
        public string CounterC_Status { get; set; }
        public Nullable<int> CounterC_OfficerID { get; set; }
    
        public virtual ApplicationForm ApplicationForm { get; set; }
    }
}
